"""Password hashing and signed access-token helpers.

The helpers here intentionally use Python's standard library to keep the sample
backend small. They still preserve the important boundaries: plaintext
passwords are only accepted at verification time, stored password values are
PBKDF2 hashes, and access tokens are signed before protected routes trust them.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import secrets
import time
from typing import Any


PASSWORD_ITERATIONS = 120_000


class TokenError(ValueError):
    """Raised when a signed access token cannot be decoded or trusted."""


def _b64encode(data: bytes) -> str:
    """Encode bytes with URL-safe base64 and no padding for compact tokens."""
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _b64decode(data: str) -> bytes:
    """Decode URL-safe base64 token parts that omit padding."""
    padding = "=" * (-len(data) % 4)
    return base64.urlsafe_b64decode(data + padding)


def hash_password(password: str, *, salt: str | None = None) -> str:
    """Hash a plaintext password with PBKDF2-SHA256.

    Args:
        password: Plaintext password supplied by configuration or the user.
        salt: Optional deterministic salt for seeded development credentials.

    Returns:
        A portable hash string containing algorithm, iterations, salt, and hash.
    """
    salt_value = salt or secrets.token_hex(16)
    derived = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt_value.encode("utf-8"),
        PASSWORD_ITERATIONS,
    )
    return f"pbkdf2_sha256${PASSWORD_ITERATIONS}${salt_value}${_b64encode(derived)}"


def verify_password(password: str, password_hash: str) -> bool:
    """Compare a plaintext password with a stored password hash.

    Args:
        password: Plaintext candidate from a login request.
        password_hash: Stored hash generated by hash_password.

    Returns:
        True only when the hash format is valid and the derived hashes match.
    """
    try:
        algorithm, iterations_raw, salt, expected = password_hash.split("$", 3)
        iterations = int(iterations_raw)
    except ValueError:
        return False

    if algorithm != "pbkdf2_sha256":
        return False

    derived = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt.encode("utf-8"),
        iterations,
    )
    actual = _b64encode(derived)
    # Constant-time comparison avoids leaking partial hash matches by timing.
    return secrets.compare_digest(actual, expected)


def create_access_token(subject: str, secret: str, expires_in_seconds: int) -> str:
    """Create a compact signed bearer token for one authenticated subject.

    Args:
        subject: Stable user identifier stored in the token's sub claim.
        secret: HMAC signing secret used by both creation and validation.
        expires_in_seconds: Number of seconds before the token expires.

    Returns:
        A two-part token: base64 JSON payload plus HMAC signature.
    """
    now = int(time.time())
    payload = {"sub": subject, "iat": now, "exp": now + expires_in_seconds}
    payload_part = _b64encode(json.dumps(payload, separators=(",", ":")).encode("utf-8"))
    signature = hmac.new(secret.encode("utf-8"), payload_part.encode("ascii"), hashlib.sha256).digest()
    return f"{payload_part}.{_b64encode(signature)}"


def decode_access_token(token: str, secret: str) -> dict[str, Any]:
    """Validate and decode a signed access token.

    Args:
        token: Bearer token received from the Authorization header.
        secret: HMAC signing secret expected for this application.

    Raises:
        TokenError: If the token is malformed, expired, unsigned, or missing a
            subject.

    Returns:
        Decoded token payload after signature and expiration checks.
    """
    try:
        payload_part, signature_part = token.split(".", 1)
    except ValueError as exc:
        raise TokenError("Malformed token") from exc

    expected_signature = hmac.new(
        secret.encode("utf-8"),
        payload_part.encode("ascii"),
        hashlib.sha256,
    ).digest()
    try:
        supplied_signature = _b64decode(signature_part)
    except ValueError as exc:
        raise TokenError("Malformed token signature") from exc

    # Never trust payload content until the signature proves it was issued here.
    if not hmac.compare_digest(supplied_signature, expected_signature):
        raise TokenError("Invalid token signature")

    try:
        payload = json.loads(_b64decode(payload_part).decode("utf-8"))
    except (ValueError, json.JSONDecodeError) as exc:
        raise TokenError("Malformed token payload") from exc

    if int(payload.get("exp", 0)) < int(time.time()):
        raise TokenError("Expired token")
    if not payload.get("sub"):
        raise TokenError("Missing token subject")
    return payload
